version: "3.8"

services:
        quarkus-service:
                build:
                        context: .
                        dockerfile: src/main/docker/Dockerfile.native
                image: mepv/vehicle-microservice:1.0.0-SNAPSHOT
                mem_limit: 128m
                environment:
                        - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://quarkus-db:5432/vehicles_db
                ports:
                        - "8080:8080"
                depends_on:
                        quarkus-db:
                                condition: service_healthy

        quarkus-db:
                image: postgres:alpine
                mem_limit: 128m
                volumes:
                        - "./src/main/resources/import.sql:/docker-entrypoint-initdb.d/import.sql"
                environment:
                        - POSTGRES_DB=vehicles_db
                        - POSTGRES_USER=mariopalacios
                        - POSTGRES_PASSWORD=pass
                healthcheck:
                        test: ["CMD-SHELL", "pg_isready -U mariopalacios"]
                        interval: 5s
                        timeout: 5s
                        retries: 6
                ports:
                        - "5432:5432"
